#!/usr/bin/env python3
##
## EPITECH PROJECT, 2019
## 202unsold_2018
## File description:
## 202unsold
##

from unsold import *

if __name__ == "__main__":
    if len(argv) == 2 and argv[1] == '-h':
        helper()
        exit(0)
    elif len(argv) == 3 and argv[1].isnumeric() and argv[2].isnumeric():
        values = [int(argv[1]), int(argv[2])]
        if values[0] <= 50 or values[1] <= 50:
            error()
        else:
            exit(unsold(values))
    else:
        error()
